language: android

jdk:
- oraclejdk8

# Global variables
env:
  global:
  - ANDROID_SDK_VERISON=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
  # Build tools
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION

  # Android SDK Version
  - android-$ANDROID_SDK_VERISON

  # System Images for running emulation
  - sys-img-x86-android-26
  - sys-img-armeabi-v7a-android-17

# Licenses that need accepting
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

# Generating folder with license agreements
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

# Use gradle for builds
script:
  - ./gradlew build check